
'use client'

import { useRef } from 'react'
import type { Donation } from '@/lib/api'
import { formatBDT } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Download } from 'lucide-react'

interface ReceiptDownloadProps {
  donation: Donation
}

export default function ReceiptDownload({ donation }: ReceiptDownloadProps) {
  const receiptRef = useRef<HTMLDivElement>(null)

  const donorName     = donation.isAnonymous ? 'Anonymous' : donation.donor?.name ?? 'Unknown'
  const campaignTitle = donation.campaign?.title ?? 'Unknown Campaign'
  const statusLabel   = donation.status.charAt(0).toUpperCase() + donation.status.slice(1).toLowerCase()

  const handlePrint = () => {
    const receiptHTML = `
      <html>
        <head>
          <title>Donation Receipt — FundRaise BD</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: Arial, sans-serif; color: #1e293b; background: #fff; padding: 40px; }
            .header { text-align: center; border-bottom: 2px solid #059669; padding-bottom: 20px; margin-bottom: 24px; }
            .logo  { font-size: 22px; font-weight: 700; color: #059669; }
            .title { font-size: 14px; color: #64748b; margin-top: 4px; }
            .badge { display: inline-block; background: #d1fae5; color: #065f46; font-size: 11px;
                     font-weight: 600; padding: 3px 10px; border-radius: 20px; margin-top: 8px; }
            .amount-box { background: #f0fdf4; border: 1px solid #a7f3d0; border-radius: 10px;
                          text-align: center; padding: 20px; margin-bottom: 24px; }
            .amount-label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
            .amount-value { font-size: 36px; font-weight: 700; color: #059669; margin-top: 4px; }
            .row  { display: flex; justify-content: space-between; padding: 10px 0;
                    border-bottom: 1px dashed #e2e8f0; font-size: 13px; }
            .row:last-child { border-bottom: none; }
            .row .key  { color: #64748b; }
            .row .val  { font-weight: 600; color: #1e293b; text-align: right; max-width: 60%; }
            .footer { margin-top: 28px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">FundRaise BD</div>
            <div class="title">Donation Receipt</div>
            <span class="badge">✓ Payment Confirmed</span>
          </div>
          <div class="amount-box">
            <div class="amount-label">Total Donated</div>
            <div class="amount-value">${formatBDT(donation.amount)}</div>
          </div>
          <div class="row"><span class="key">Receipt No.</span><span class="val">${donation.id.toUpperCase()}</span></div>
          <div class="row"><span class="key">Donor</span><span class="val">${donorName}</span></div>
          <div class="row"><span class="key">Campaign</span><span class="val">${campaignTitle}</span></div>
          <div class="row"><span class="key">Amount</span><span class="val">${formatBDT(donation.amount)}</span></div>
          <div class="row"><span class="key">Status</span><span class="val" style="color:#059669">${statusLabel}</span></div>
          <div class="row"><span class="key">Date</span><span class="val">${new Date(donation.createdAt).toLocaleDateString('en-BD', { day: '2-digit', month: 'long', year: 'numeric' })}</span></div>
          ${donation.message ? `<div class="row"><span class="key">Message</span><span class="val">${donation.message}</span></div>` : ''}
          <div class="footer">
            Thank you for your generosity. This receipt is auto-generated by FundRaise BD.<br/>
            Printed on ${new Date().toLocaleDateString('en-BD', { day: '2-digit', month: 'long', year: 'numeric' })}
          </div>
        </body>
      </html>
    `

    const printWindow = window.open('', '_blank', 'width=600,height=800')
    if (!printWindow) return
    printWindow.document.write(receiptHTML)
    printWindow.document.close()
    printWindow.onload = () => {
      printWindow.focus()
      printWindow.print()
      printWindow.close()
    }
  }

  return (
    <div ref={receiptRef}>
      <Button
        onClick={handlePrint}
        variant="outline"
        size="sm"
        className="flex items-center gap-1.5 text-xs border-gray-200 text-slate-600 hover:border-emerald-400 hover:text-emerald-700 rounded-lg"
      >
        <Download size={13} />
        Download Receipt
      </Button>
    </div>
  )
}